'use client'
import Header from '@/components/header/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation'


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const pathname = usePathname()

    return (
        <html lang="en" className='bg-[#f7f7f7]'>
            <body className={inter.className}>
                {
                    !pathname.startsWith('/login') && 
                    <Header /> 
                } 
                {children}
            </body>
        </html>
    )
}
